-- Jalankan seluruh file ini di Supabase SQL Editor.
create table if not exists public.menus (
 id bigint generated by default as identity primary key,
 menu_date date not null unique,
 day_name text not null default '',
 menu_title text not null default 'Paket Makan Bergizi Gratis',
 menu_description text not null default '',
 carbohydrate text not null default '', animal_protein text not null default '',
 plant_protein text not null default '', vegetable text not null default '', fruit text not null default '',
 energy_small text not null default '', energy_large text not null default '',
 protein_small text not null default '', protein_large text not null default '',
 fat_small text not null default '', fat_large text not null default '',
 carb_small text not null default '', carb_large text not null default '',
 fiber_small text not null default '', fiber_large text not null default '',
 photo_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.menus enable row level security;
drop policy if exists "Public can read menus" on public.menus;
create policy "Public can read menus" on public.menus for select to anon,authenticated using (true);
drop policy if exists "Authenticated users can insert menus" on public.menus;
create policy "Authenticated users can insert menus" on public.menus for insert to authenticated with check (true);
drop policy if exists "Authenticated users can update menus" on public.menus;
create policy "Authenticated users can update menus" on public.menus for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated users can delete menus" on public.menus;
create policy "Authenticated users can delete menus" on public.menus for delete to authenticated using (true);

insert into storage.buckets(id,name,public) values('menu-photos','menu-photos',true) on conflict(id) do update set public=true;
drop policy if exists "Public can view menu photos" on storage.objects;
create policy "Public can view menu photos" on storage.objects for select to anon,authenticated using(bucket_id='menu-photos');
drop policy if exists "Authenticated users can upload menu photos" on storage.objects;
create policy "Authenticated users can upload menu photos" on storage.objects for insert to authenticated with check(bucket_id='menu-photos');
drop policy if exists "Authenticated users can update menu photos" on storage.objects;
create policy "Authenticated users can update menu photos" on storage.objects for update to authenticated using(bucket_id='menu-photos') with check(bucket_id='menu-photos');
drop policy if exists "Authenticated users can delete menu photos" on storage.objects;
create policy "Authenticated users can delete menu photos" on storage.objects for delete to authenticated using(bucket_id='menu-photos');

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists menus_set_updated_at on public.menus;
create trigger menus_set_updated_at before update on public.menus for each row execute function public.set_updated_at();
